name: build & test
on: [push]

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    container: tonyodell/rakudo-nightly:latest
    steps:
      - name: os deps
        run: |
          apt update && \
          apt install -y git zlib1g zlib1g-dev
      - name: clone
        run: git clone -b "${GITHUB_REF##*/}" https://github.com/tony-o/raku-fez ./fez
      - name: module deps
        run: cd ./fez && zef install --deps-only --debug .
      - name: test & installs ok
        run: cd ./fez && zef install .
